### ISSUE TITLE
health handler

### ISSUE THREAD

**Issue by zkryaev** [PetrGrachev/TimeLine-analytics#1]
Сделать ручку /analytics/health, чтобы при поднятии докер контейнера можно было понять, что контейнер живой.

Пример из minio:
```
healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
        interval: 30s
        timeout: 20s
        retries: 3
```
Аналогично для сервиса:
```
healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:5000/analytics/health"]
        interval: 30s
        timeout: 20s
        retries: 3
```
